FROM openjdk:8-jre

ENV POWERAPI_PACKAGE powerapi-code-energy-analysis
ENV LIBPFM_PACKAGE libpfm-4.6.0

ENV INSTALL_PACKAGES wget make gcc
ENV RUNTIME_PACKAGES cgroup-tools

COPY ${POWERAPI_PACKAGE}/target/universal/${POWERAPI_PACKAGE} /root/${POWERAPI_PACKAGE}/

VOLUME /conf /tmp

RUN apt-get update && apt-get -y upgrade && apt-get -y install $INSTALL_PACKAGES $RUNTIME_PACKAGES && \
  wget http://downloads.sourceforge.net/project/perfmon2/libpfm4/${LIBPFM_PACKAGE}.tar.gz && tar -C /root -xzvf ${LIBPFM_PACKAGE}.tar.gz && (cd /root/$LIBPFM_PACKAGE; make lib; make install) && rm -rf /root/$LIBPFM_PACKAGE ${LIBPFM_PACKAGE}.tar.gz && \
  rm -rf /root/${POWERAPI_PACKAGE}/conf && ln -s /conf/ /root/${POWERAPI_PACKAGE}/conf && \
  apt-get -y remove --auto-remove $INSTALL_PACKAGES && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /root/$POWERAPI_PACKAGE

ENTRYPOINT ["./bin/powerapi"]
