FROM alpine:latest

ENV POWERAPI_PACKAGE powerapi-sampling
ENV LIBPFM_PACKAGE libpfm-4.6.0

ENV INSTALL_PACKAGES ca-certificates linux-headers libc-dev make gcc patch
ENV RUNTIME_PACKAGES bluez bluez-dev openjdk7-jre bash util-linux cpulimit procps

COPY docker/libpfm/config.mk.patch /root/
COPY docker/sampling/run.sh /root/
COPY ${POWERAPI_PACKAGE}/target/universal/${POWERAPI_PACKAGE}/ /root/${POWERAPI_PACKAGE}/

VOLUME /conf

RUN apk update && apk upgrade && apk add $INSTALL_PACKAGES $RUNTIME_PACKAGES && \
  wget https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/6/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-2.21-r2.apk && apk --allow-untrusted add glibc-2.21-r2.apk && rm -f glibc-2.21-r2.apk && \
  wget http://downloads.sourceforge.net/project/perfmon2/libpfm4/${LIBPFM_PACKAGE}.tar.gz && tar -C /root -xzvf ${LIBPFM_PACKAGE}.tar.gz && patch -d /root/$LIBPFM_PACKAGE -p1 < /root/config.mk.patch && (cd /root/$LIBPFM_PACKAGE; make lib; make install) && rm -rf /root/config.mk.patch /root/$LIBPFM_PACKAGE ${LIBPFM_PACKAGE}.tar.gz && \
  wget http://people.seas.harvard.edu/~apw/stress/stress-1.0.4.tar.gz && tar -C /root -xzvf stress-1.0.4.tar.gz && (cd /root/stress-1.0.4; ./configure; make; make install) && rm -rf /root/stress-1.0.4 && \
  rm -rf /${POWERAPI_PACKAGE}/conf && ln -s /conf/ /root/${POWERAPI_PACKAGE}/conf && \
  apk del glibc $INSTALL_PACKAGES && \
  rm -rf /var/cache/apk/*

WORKDIR /root

ENTRYPOINT ["./run.sh"]
