FROM openjdk:8-jre

ENV POWERAPI_PACKAGE powerapi-sampling-cpu

ENV INSTALL_PACKAGES build-essential git
ENV RUNTIME_PACKAGES module-init-tools cpulimit psmisc

COPY docker/sampling/config.mk.patch /root/
COPY docker/sampling/run.sh /root/
COPY ${POWERAPI_PACKAGE}/target/universal/${POWERAPI_PACKAGE}/ /root/${POWERAPI_PACKAGE}/

RUN apt-get update && apt-get install -y $INSTALL_PACKAGES $RUNTIME_PACKAGES \
    && cd /root && wget http://people.seas.harvard.edu/~apw/stress/stress-1.0.4.tar.gz && tar -xzvf stress-1.0.4.tar.gz && (cd stress-1.0.4; ./configure; make; make install) && rm -rf stress-1.0.4 stress-1.0.4.tar.gz && cd / \
    && cd /root && git clone https://github.com/mcolmant/likwid.git && (cd likwid;  git apply < ../config.mk.patch; make; make install) && rm -rf likwid config.mk.patch && cd / \
    && apt-get autoremove -y $INSTALL_PACKAGES \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root

ENTRYPOINT ["./run.sh"]