/*
 * Generated by the protobluff compiler - do not edit.
 * ----------------------------------------------------------------------------
 * Date:     03/29/16 14:06:32
 * Filename: payload.proto
 * Package:  -
 * ----------------------------------------------------------------------------
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#include <protobluff/descriptor.h>

#include "payload.pb.h"

/* ----------------------------------------------------------------------------
 * Descriptors
 * ------------------------------------------------------------------------- */

/* MapEntry : descriptor */
pb_descriptor_t
mapentry_descriptor = { {
  (const pb_field_descriptor_t []){

    /* required string key = 1 */
    { .tag   = 1,
      .name  = "key",
      .type  = STRING,
      .label = REQUIRED },

    /* required uint64 value = 2 */
    { .tag   = 2,
      .name  = "value",
      .type  = UINT64,
      .label = REQUIRED }

  }, 2 } };

/* Payload : descriptor */
pb_descriptor_t
payload_descriptor = { {
  (const pb_field_descriptor_t []){

    /* required uint32 core = 1 */
    { .tag   = 1,
      .name  = "core",
      .type  = UINT32,
      .label = REQUIRED },

    /* required uint32 pid = 2 */
    { .tag   = 2,
      .name  = "pid",
      .type  = UINT32,
      .label = REQUIRED },

    /* required uint32 tid = 3 */
    { .tag   = 3,
      .name  = "tid",
      .type  = UINT32,
      .label = REQUIRED },

    /* required uint64 timestamp = 4 */
    { .tag   = 4,
      .name  = "timestamp",
      .type  = UINT64,
      .label = REQUIRED },

    /* repeated MapEntry counters = 5 */
    { .tag   = 5,
      .name  = "counters",
      .type  = MESSAGE,
      .label = REPEATED,
      .refer = &mapentry_descriptor },

    /* repeated string traces = 6 */
    { .tag   = 6,
      .name  = "traces",
      .type  = STRING,
      .label = REPEATED }

  }, 6 } };

