# Adapted from frolvlad/alpine-python-machinelearning
FROM frolvlad/alpine-python3

COPY docker/watchdog/watchdog.py /root/

RUN apk add --no-cache libstdc++ && \
    apk add --no-cache \
        --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
        lapack-dev && \
    apk add --no-cache \
        --virtual=.build-dependencies \
        g++ gfortran musl-dev \
        python3-dev && \
    ln -s locale.h /usr/include/xlocale.h && \
    pip install cython && \
    pip install numpy && \
    pip install scipy && \
    pip install scikit-learn && \
    pip install pandas==0.19.1 && \
    pip install click && \
    pip install influxdb && \
    pip install kazoo && \
    pip uninstall --yes cython && \
    rm /usr/include/xlocale.h && \
    rm -r /root/.cache && \
    apk del .build-dependencies

ENTRYPOINT ["python3", "/root/watchdog.py"]