// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payload.proto

package org.powerapi.module.libpfm;

public final class PayloadProtocol {
  private PayloadProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MapEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MapEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string key = 1;</code>
     */
    boolean hasKey();
    /**
     * <code>required string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required uint64 value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required uint64 value = 2;</code>
     */
    long getValue();
  }
  /**
   * Protobuf type {@code MapEntry}
   */
  public static final class MapEntry extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MapEntry)
      MapEntryOrBuilder {
    // Use MapEntry.newBuilder() to construct.
    private MapEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MapEntry(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MapEntry defaultInstance;
    public static MapEntry getDefaultInstance() {
      return defaultInstance;
    }

    public MapEntry getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MapEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              key_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.powerapi.module.libpfm.PayloadProtocol.internal_static_MapEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.powerapi.module.libpfm.PayloadProtocol.internal_static_MapEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.powerapi.module.libpfm.PayloadProtocol.MapEntry.class, org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder.class);
    }

    public static com.google.protobuf.Parser<MapEntry> PARSER =
        new com.google.protobuf.AbstractParser<MapEntry>() {
      public MapEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MapEntry(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MapEntry> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private java.lang.Object key_;
    /**
     * <code>required string key = 1;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private long value_;
    /**
     * <code>required uint64 value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 value = 2;</code>
     */
    public long getValue() {
      return value_;
    }

    private void initFields() {
      key_ = "";
      value_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.powerapi.module.libpfm.PayloadProtocol.MapEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.MapEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.MapEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.MapEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.MapEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.MapEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.MapEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.MapEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.MapEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.MapEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.powerapi.module.libpfm.PayloadProtocol.MapEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MapEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MapEntry)
        org.powerapi.module.libpfm.PayloadProtocol.MapEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.powerapi.module.libpfm.PayloadProtocol.internal_static_MapEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.powerapi.module.libpfm.PayloadProtocol.internal_static_MapEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.powerapi.module.libpfm.PayloadProtocol.MapEntry.class, org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder.class);
      }

      // Construct using org.powerapi.module.libpfm.PayloadProtocol.MapEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.powerapi.module.libpfm.PayloadProtocol.internal_static_MapEntry_descriptor;
      }

      public org.powerapi.module.libpfm.PayloadProtocol.MapEntry getDefaultInstanceForType() {
        return org.powerapi.module.libpfm.PayloadProtocol.MapEntry.getDefaultInstance();
      }

      public org.powerapi.module.libpfm.PayloadProtocol.MapEntry build() {
        org.powerapi.module.libpfm.PayloadProtocol.MapEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.powerapi.module.libpfm.PayloadProtocol.MapEntry buildPartial() {
        org.powerapi.module.libpfm.PayloadProtocol.MapEntry result = new org.powerapi.module.libpfm.PayloadProtocol.MapEntry(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.powerapi.module.libpfm.PayloadProtocol.MapEntry) {
          return mergeFrom((org.powerapi.module.libpfm.PayloadProtocol.MapEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.powerapi.module.libpfm.PayloadProtocol.MapEntry other) {
        if (other == org.powerapi.module.libpfm.PayloadProtocol.MapEntry.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.powerapi.module.libpfm.PayloadProtocol.MapEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.powerapi.module.libpfm.PayloadProtocol.MapEntry) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 1;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      private long value_ ;
      /**
       * <code>required uint64 value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 value = 2;</code>
       */
      public long getValue() {
        return value_;
      }
      /**
       * <code>required uint64 value = 2;</code>
       */
      public Builder setValue(long value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MapEntry)
    }

    static {
      defaultInstance = new MapEntry(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MapEntry)
  }

  public interface PayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Payload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 core = 1;</code>
     */
    boolean hasCore();
    /**
     * <code>required uint32 core = 1;</code>
     */
    int getCore();

    /**
     * <code>required uint32 pid = 2;</code>
     */
    boolean hasPid();
    /**
     * <code>required uint32 pid = 2;</code>
     */
    int getPid();

    /**
     * <code>required uint32 tid = 3;</code>
     */
    boolean hasTid();
    /**
     * <code>required uint32 tid = 3;</code>
     */
    int getTid();

    /**
     * <code>required uint64 timestamp = 4;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required uint64 timestamp = 4;</code>
     */
    long getTimestamp();

    /**
     * <code>repeated .MapEntry counters = 5;</code>
     */
    java.util.List<org.powerapi.module.libpfm.PayloadProtocol.MapEntry> 
        getCountersList();
    /**
     * <code>repeated .MapEntry counters = 5;</code>
     */
    org.powerapi.module.libpfm.PayloadProtocol.MapEntry getCounters(int index);
    /**
     * <code>repeated .MapEntry counters = 5;</code>
     */
    int getCountersCount();
    /**
     * <code>repeated .MapEntry counters = 5;</code>
     */
    java.util.List<? extends org.powerapi.module.libpfm.PayloadProtocol.MapEntryOrBuilder> 
        getCountersOrBuilderList();
    /**
     * <code>repeated .MapEntry counters = 5;</code>
     */
    org.powerapi.module.libpfm.PayloadProtocol.MapEntryOrBuilder getCountersOrBuilder(
        int index);

    /**
     * <code>repeated string traces = 6;</code>
     */
    com.google.protobuf.ProtocolStringList
        getTracesList();
    /**
     * <code>repeated string traces = 6;</code>
     */
    int getTracesCount();
    /**
     * <code>repeated string traces = 6;</code>
     */
    java.lang.String getTraces(int index);
    /**
     * <code>repeated string traces = 6;</code>
     */
    com.google.protobuf.ByteString
        getTracesBytes(int index);
  }
  /**
   * Protobuf type {@code Payload}
   */
  public static final class Payload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Payload)
      PayloadOrBuilder {
    // Use Payload.newBuilder() to construct.
    private Payload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Payload(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Payload defaultInstance;
    public static Payload getDefaultInstance() {
      return defaultInstance;
    }

    public Payload getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Payload(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              core_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              pid_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              tid_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readUInt64();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                counters_ = new java.util.ArrayList<org.powerapi.module.libpfm.PayloadProtocol.MapEntry>();
                mutable_bitField0_ |= 0x00000010;
              }
              counters_.add(input.readMessage(org.powerapi.module.libpfm.PayloadProtocol.MapEntry.PARSER, extensionRegistry));
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                traces_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              traces_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          counters_ = java.util.Collections.unmodifiableList(counters_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          traces_ = traces_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.powerapi.module.libpfm.PayloadProtocol.internal_static_Payload_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.powerapi.module.libpfm.PayloadProtocol.internal_static_Payload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.powerapi.module.libpfm.PayloadProtocol.Payload.class, org.powerapi.module.libpfm.PayloadProtocol.Payload.Builder.class);
    }

    public static com.google.protobuf.Parser<Payload> PARSER =
        new com.google.protobuf.AbstractParser<Payload>() {
      public Payload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Payload(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Payload> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CORE_FIELD_NUMBER = 1;
    private int core_;
    /**
     * <code>required uint32 core = 1;</code>
     */
    public boolean hasCore() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 core = 1;</code>
     */
    public int getCore() {
      return core_;
    }

    public static final int PID_FIELD_NUMBER = 2;
    private int pid_;
    /**
     * <code>required uint32 pid = 2;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 pid = 2;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int TID_FIELD_NUMBER = 3;
    private int tid_;
    /**
     * <code>required uint32 tid = 3;</code>
     */
    public boolean hasTid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 tid = 3;</code>
     */
    public int getTid() {
      return tid_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>required uint64 timestamp = 4;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int COUNTERS_FIELD_NUMBER = 5;
    private java.util.List<org.powerapi.module.libpfm.PayloadProtocol.MapEntry> counters_;
    /**
     * <code>repeated .MapEntry counters = 5;</code>
     */
    public java.util.List<org.powerapi.module.libpfm.PayloadProtocol.MapEntry> getCountersList() {
      return counters_;
    }
    /**
     * <code>repeated .MapEntry counters = 5;</code>
     */
    public java.util.List<? extends org.powerapi.module.libpfm.PayloadProtocol.MapEntryOrBuilder> 
        getCountersOrBuilderList() {
      return counters_;
    }
    /**
     * <code>repeated .MapEntry counters = 5;</code>
     */
    public int getCountersCount() {
      return counters_.size();
    }
    /**
     * <code>repeated .MapEntry counters = 5;</code>
     */
    public org.powerapi.module.libpfm.PayloadProtocol.MapEntry getCounters(int index) {
      return counters_.get(index);
    }
    /**
     * <code>repeated .MapEntry counters = 5;</code>
     */
    public org.powerapi.module.libpfm.PayloadProtocol.MapEntryOrBuilder getCountersOrBuilder(
        int index) {
      return counters_.get(index);
    }

    public static final int TRACES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList traces_;
    /**
     * <code>repeated string traces = 6;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTracesList() {
      return traces_;
    }
    /**
     * <code>repeated string traces = 6;</code>
     */
    public int getTracesCount() {
      return traces_.size();
    }
    /**
     * <code>repeated string traces = 6;</code>
     */
    public java.lang.String getTraces(int index) {
      return traces_.get(index);
    }
    /**
     * <code>repeated string traces = 6;</code>
     */
    public com.google.protobuf.ByteString
        getTracesBytes(int index) {
      return traces_.getByteString(index);
    }

    private void initFields() {
      core_ = 0;
      pid_ = 0;
      tid_ = 0;
      timestamp_ = 0L;
      counters_ = java.util.Collections.emptyList();
      traces_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getCountersCount(); i++) {
        if (!getCounters(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, core_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, pid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, tid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, timestamp_);
      }
      for (int i = 0; i < counters_.size(); i++) {
        output.writeMessage(5, counters_.get(i));
      }
      for (int i = 0; i < traces_.size(); i++) {
        output.writeBytes(6, traces_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, core_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, pid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, tid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, timestamp_);
      }
      for (int i = 0; i < counters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, counters_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < traces_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(traces_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTracesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.powerapi.module.libpfm.PayloadProtocol.Payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.Payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.Payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.Payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.Payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.Payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.Payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.Payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.Payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.powerapi.module.libpfm.PayloadProtocol.Payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.powerapi.module.libpfm.PayloadProtocol.Payload prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Payload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Payload)
        org.powerapi.module.libpfm.PayloadProtocol.PayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.powerapi.module.libpfm.PayloadProtocol.internal_static_Payload_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.powerapi.module.libpfm.PayloadProtocol.internal_static_Payload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.powerapi.module.libpfm.PayloadProtocol.Payload.class, org.powerapi.module.libpfm.PayloadProtocol.Payload.Builder.class);
      }

      // Construct using org.powerapi.module.libpfm.PayloadProtocol.Payload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCountersFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        core_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        tid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (countersBuilder_ == null) {
          counters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          countersBuilder_.clear();
        }
        traces_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.powerapi.module.libpfm.PayloadProtocol.internal_static_Payload_descriptor;
      }

      public org.powerapi.module.libpfm.PayloadProtocol.Payload getDefaultInstanceForType() {
        return org.powerapi.module.libpfm.PayloadProtocol.Payload.getDefaultInstance();
      }

      public org.powerapi.module.libpfm.PayloadProtocol.Payload build() {
        org.powerapi.module.libpfm.PayloadProtocol.Payload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.powerapi.module.libpfm.PayloadProtocol.Payload buildPartial() {
        org.powerapi.module.libpfm.PayloadProtocol.Payload result = new org.powerapi.module.libpfm.PayloadProtocol.Payload(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.core_ = core_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.pid_ = pid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tid_ = tid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        if (countersBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            counters_ = java.util.Collections.unmodifiableList(counters_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.counters_ = counters_;
        } else {
          result.counters_ = countersBuilder_.build();
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          traces_ = traces_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.traces_ = traces_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.powerapi.module.libpfm.PayloadProtocol.Payload) {
          return mergeFrom((org.powerapi.module.libpfm.PayloadProtocol.Payload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.powerapi.module.libpfm.PayloadProtocol.Payload other) {
        if (other == org.powerapi.module.libpfm.PayloadProtocol.Payload.getDefaultInstance()) return this;
        if (other.hasCore()) {
          setCore(other.getCore());
        }
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (other.hasTid()) {
          setTid(other.getTid());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (countersBuilder_ == null) {
          if (!other.counters_.isEmpty()) {
            if (counters_.isEmpty()) {
              counters_ = other.counters_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureCountersIsMutable();
              counters_.addAll(other.counters_);
            }
            onChanged();
          }
        } else {
          if (!other.counters_.isEmpty()) {
            if (countersBuilder_.isEmpty()) {
              countersBuilder_.dispose();
              countersBuilder_ = null;
              counters_ = other.counters_;
              bitField0_ = (bitField0_ & ~0x00000010);
              countersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCountersFieldBuilder() : null;
            } else {
              countersBuilder_.addAllMessages(other.counters_);
            }
          }
        }
        if (!other.traces_.isEmpty()) {
          if (traces_.isEmpty()) {
            traces_ = other.traces_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureTracesIsMutable();
            traces_.addAll(other.traces_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCore()) {
          
          return false;
        }
        if (!hasPid()) {
          
          return false;
        }
        if (!hasTid()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        for (int i = 0; i < getCountersCount(); i++) {
          if (!getCounters(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.powerapi.module.libpfm.PayloadProtocol.Payload parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.powerapi.module.libpfm.PayloadProtocol.Payload) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int core_ ;
      /**
       * <code>required uint32 core = 1;</code>
       */
      public boolean hasCore() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 core = 1;</code>
       */
      public int getCore() {
        return core_;
      }
      /**
       * <code>required uint32 core = 1;</code>
       */
      public Builder setCore(int value) {
        bitField0_ |= 0x00000001;
        core_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 core = 1;</code>
       */
      public Builder clearCore() {
        bitField0_ = (bitField0_ & ~0x00000001);
        core_ = 0;
        onChanged();
        return this;
      }

      private int pid_ ;
      /**
       * <code>required uint32 pid = 2;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 pid = 2;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required uint32 pid = 2;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000002;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 pid = 2;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        pid_ = 0;
        onChanged();
        return this;
      }

      private int tid_ ;
      /**
       * <code>required uint32 tid = 3;</code>
       */
      public boolean hasTid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 tid = 3;</code>
       */
      public int getTid() {
        return tid_;
      }
      /**
       * <code>required uint32 tid = 3;</code>
       */
      public Builder setTid(int value) {
        bitField0_ |= 0x00000004;
        tid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 tid = 3;</code>
       */
      public Builder clearTid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tid_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>required uint64 timestamp = 4;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required uint64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<org.powerapi.module.libpfm.PayloadProtocol.MapEntry> counters_ =
        java.util.Collections.emptyList();
      private void ensureCountersIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          counters_ = new java.util.ArrayList<org.powerapi.module.libpfm.PayloadProtocol.MapEntry>(counters_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.powerapi.module.libpfm.PayloadProtocol.MapEntry, org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder, org.powerapi.module.libpfm.PayloadProtocol.MapEntryOrBuilder> countersBuilder_;

      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public java.util.List<org.powerapi.module.libpfm.PayloadProtocol.MapEntry> getCountersList() {
        if (countersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(counters_);
        } else {
          return countersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public int getCountersCount() {
        if (countersBuilder_ == null) {
          return counters_.size();
        } else {
          return countersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public org.powerapi.module.libpfm.PayloadProtocol.MapEntry getCounters(int index) {
        if (countersBuilder_ == null) {
          return counters_.get(index);
        } else {
          return countersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public Builder setCounters(
          int index, org.powerapi.module.libpfm.PayloadProtocol.MapEntry value) {
        if (countersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountersIsMutable();
          counters_.set(index, value);
          onChanged();
        } else {
          countersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public Builder setCounters(
          int index, org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder builderForValue) {
        if (countersBuilder_ == null) {
          ensureCountersIsMutable();
          counters_.set(index, builderForValue.build());
          onChanged();
        } else {
          countersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public Builder addCounters(org.powerapi.module.libpfm.PayloadProtocol.MapEntry value) {
        if (countersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountersIsMutable();
          counters_.add(value);
          onChanged();
        } else {
          countersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public Builder addCounters(
          int index, org.powerapi.module.libpfm.PayloadProtocol.MapEntry value) {
        if (countersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountersIsMutable();
          counters_.add(index, value);
          onChanged();
        } else {
          countersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public Builder addCounters(
          org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder builderForValue) {
        if (countersBuilder_ == null) {
          ensureCountersIsMutable();
          counters_.add(builderForValue.build());
          onChanged();
        } else {
          countersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public Builder addCounters(
          int index, org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder builderForValue) {
        if (countersBuilder_ == null) {
          ensureCountersIsMutable();
          counters_.add(index, builderForValue.build());
          onChanged();
        } else {
          countersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public Builder addAllCounters(
          java.lang.Iterable<? extends org.powerapi.module.libpfm.PayloadProtocol.MapEntry> values) {
        if (countersBuilder_ == null) {
          ensureCountersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, counters_);
          onChanged();
        } else {
          countersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public Builder clearCounters() {
        if (countersBuilder_ == null) {
          counters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          countersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public Builder removeCounters(int index) {
        if (countersBuilder_ == null) {
          ensureCountersIsMutable();
          counters_.remove(index);
          onChanged();
        } else {
          countersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder getCountersBuilder(
          int index) {
        return getCountersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public org.powerapi.module.libpfm.PayloadProtocol.MapEntryOrBuilder getCountersOrBuilder(
          int index) {
        if (countersBuilder_ == null) {
          return counters_.get(index);  } else {
          return countersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public java.util.List<? extends org.powerapi.module.libpfm.PayloadProtocol.MapEntryOrBuilder> 
           getCountersOrBuilderList() {
        if (countersBuilder_ != null) {
          return countersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(counters_);
        }
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder addCountersBuilder() {
        return getCountersFieldBuilder().addBuilder(
            org.powerapi.module.libpfm.PayloadProtocol.MapEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder addCountersBuilder(
          int index) {
        return getCountersFieldBuilder().addBuilder(
            index, org.powerapi.module.libpfm.PayloadProtocol.MapEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .MapEntry counters = 5;</code>
       */
      public java.util.List<org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder> 
           getCountersBuilderList() {
        return getCountersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.powerapi.module.libpfm.PayloadProtocol.MapEntry, org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder, org.powerapi.module.libpfm.PayloadProtocol.MapEntryOrBuilder> 
          getCountersFieldBuilder() {
        if (countersBuilder_ == null) {
          countersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.powerapi.module.libpfm.PayloadProtocol.MapEntry, org.powerapi.module.libpfm.PayloadProtocol.MapEntry.Builder, org.powerapi.module.libpfm.PayloadProtocol.MapEntryOrBuilder>(
                  counters_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          counters_ = null;
        }
        return countersBuilder_;
      }

      private com.google.protobuf.LazyStringList traces_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTracesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          traces_ = new com.google.protobuf.LazyStringArrayList(traces_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string traces = 6;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTracesList() {
        return traces_.getUnmodifiableView();
      }
      /**
       * <code>repeated string traces = 6;</code>
       */
      public int getTracesCount() {
        return traces_.size();
      }
      /**
       * <code>repeated string traces = 6;</code>
       */
      public java.lang.String getTraces(int index) {
        return traces_.get(index);
      }
      /**
       * <code>repeated string traces = 6;</code>
       */
      public com.google.protobuf.ByteString
          getTracesBytes(int index) {
        return traces_.getByteString(index);
      }
      /**
       * <code>repeated string traces = 6;</code>
       */
      public Builder setTraces(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTracesIsMutable();
        traces_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string traces = 6;</code>
       */
      public Builder addTraces(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTracesIsMutable();
        traces_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string traces = 6;</code>
       */
      public Builder addAllTraces(
          java.lang.Iterable<java.lang.String> values) {
        ensureTracesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, traces_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string traces = 6;</code>
       */
      public Builder clearTraces() {
        traces_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string traces = 6;</code>
       */
      public Builder addTracesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTracesIsMutable();
        traces_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Payload)
    }

    static {
      defaultInstance = new Payload(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Payload)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MapEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payload_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Payload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpayload.proto\"&\n\010MapEntry\022\013\n\003key\030\001 \002(\t" +
      "\022\r\n\005value\030\002 \002(\004\"q\n\007Payload\022\014\n\004core\030\001 \002(\r" +
      "\022\013\n\003pid\030\002 \002(\r\022\013\n\003tid\030\003 \002(\r\022\021\n\ttimestamp\030" +
      "\004 \002(\004\022\033\n\010counters\030\005 \003(\0132\t.MapEntry\022\016\n\006tr" +
      "aces\030\006 \003(\tB-\n\032org.powerapi.module.libpfm" +
      "B\017PayloadProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MapEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Payload_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Payload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Payload_descriptor,
        new java.lang.String[] { "Core", "Pid", "Tid", "Timestamp", "Counters", "Traces", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
